# Generated by Django 4.0.1 on 2022-01-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0003_persona_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
