# Generated by Django 4.0.1 on 2022-01-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0004_alter_persona_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
