# Generated by Django 4.0.1 on 2022-01-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0005_alter_persona_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id_user',
            field=models.CharField(max_length=20),
        ),
    ]
