# Generated by Django 4.0.1 on 2022-01-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0008_macroprocessuniverse_manageresponsableuniverse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniverseManageResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UniverseProces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=100, null=True)),
                ('macroprocess', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='MacroprocessUniverse',
            new_name='UniverseMacroproces',
        ),
        migrations.DeleteModel(
            name='manageResponsableUniverse',
        ),
        migrations.DeleteModel(
            name='ProcesesUniverse',
        ),
    ]
