# Generated by Django 4.0.1 on 2022-01-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0012_remove_universeproces_codeprocess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universemacroproces',
            old_name='codeMacro',
            new_name='numMacro',
        ),
    ]
