# Generated by Django 4.0.1 on 2022-01-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0013_rename_codemacro_universemacroproces_nummacro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universemacroproces',
            name='numMacro',
        ),
        migrations.AddField(
            model_name='universeproces',
            name='numProcess',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='universemanageresponsable',
            name='codeManage',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
