# Generated by Django 4.0.1 on 2022-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0015_universeaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniverseAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('codeAudit', models.CharField(max_length=10)),
            ],
        ),
    ]
