# Generated by Django 4.0.1 on 2022-02-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0016_universealias'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniverseCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('codeAudit', models.CharField(max_length=10)),
            ],
        ),
    ]
