# Generated by Django 4.0.1 on 2022-02-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0017_universecause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universecause',
            name='codeAudit',
        ),
    ]
