# Generated by Django 4.0.1 on 2022-02-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='municipality',
            new_name='city',
        ),
    ]
