# Generated by Django 4.0.1 on 2022-02-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_rename_municipality_audit_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='ActDetail',
            new_name='actDetail',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='deparment',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='id',
        ),
        migrations.AddField(
            model_name='audit',
            name='idAudit',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='status',
            field=models.CharField(default='pendiente', max_length=25),
        ),
    ]
