# Generated by Django 4.0.1 on 2022-02-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_rename_actdetail_audit_actdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='codeAudit',
            field=models.CharField(max_length=25),
        ),
    ]
