# Generated by Django 4.0.1 on 2022-02-08 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_audit_idaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='dateEject',
            field=models.DateField(blank=True, default=datetime.date(1111, 11, 11)),
        ),
    ]
