# Generated by Django 4.0.1 on 2022-02-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_audit_dateeject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='dateEject',
            new_name='dateExect',
        ),
    ]
